[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vesting = "BB1JtUxXtmDnb6L5qXUSfuvT18TggYuSLBzfmjoYFnb4"

[programs.devnet]
anchor_vesting = "BB1JtUxXtmDnb6L5qXUSfuvT18TggYuSLBzfmjoYFnb4"

[[test.validator.genesis]]
address = "EzRUZpW3CsvnKzEUiF7fAPHyHWsv2D3ERR482BPKHwYk"
program = "pinocchio-vesting/target/deploy/pinocchio_vesting.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.test.ts\""
